personio-personnel-data-api.yaml
Add documentation for deleting attendances. Moves error response to its own definition.
=> [DD-2022] Allow deletion of attendance period via Attendance API

personio-personnel-data-api-oa3.yaml
A new field in the attendance period GET response payload has been added to show pagination information. In this task, the specification of the pagination information is added.
=> [TM-5038] Add pagination metadata for attendance

personio-personnel-data-api-oa3.yaml, personio-personnel-data-api.yaml
For Attendances POST endpoint, introduce a detailed_message attribute to show which periods were successfully persisted and which periods returned some error, explaining the cause of the error.
=> [TT-187] Update Attendances POST error response

personio-personnel-data-api-oa3.yaml
employees=1&employees=2 -> employees[]=1&employees[]=2
=> Modify the way multi value query params are rendered

personio-personnel-data-api-oa3.yaml
**Context:** Add the documentation for two new optional parameters for doing pagination in employee API:
* offset
* limit
=> [INT] Employee API: Add pagination

personio-recruiting-api.yaml
Status Quo:
Looks like this sidebar is generated from the tags. Updated them.
=> Update names of recruiting endpoints

personio-personnel-data-api-oa3.yaml
Add documentation for the get document-categories and post documents endpoints.
=> [PAPI-178] Create documentation for the documents endpoints in the developer hub

personio-recruiting-api.yaml
=> [RCO-708] small adjustments in recruiting documentation for new readme.io version

personio-personnel-data-api-oa3.yaml
Languages where code snippets will be created for:
- cURL
- Java
- Node
- PHP
- Python
- Ruby
=> Limit Code Snippet Languages for Readme.io

personio-personnel-data-api-oa3.yaml
Added custom code snippets for not working auto-generated Readme.io code snippets
=> [PAPI-376] Cover not working auto-generated code snippets with warnings

common-components-v2.json
- Include headers
- Include pagination and cursor
- Include Errors
- Include MetaObject
- Include CreatedObject
- Include NotFoundResponse
=> [PAPI-587] - API Spec Common components

common-components-v2.json
- ReadOnly visibility for specific attributes
=> API Spec Common components

personio-personnel-data-api-oa3.yaml
This MR includes the options to set and remove supervisor id using the Employee Public API
=> [PAPI-559] Add supervisor ID in Employee post and patch endpoints

personio-personnel-data-api-oa3.yaml
Remove UTC from start_time and end_time description.
=> Fix start_time and end_time to not receive UTC

personio-personnel-data-api-oa3.yaml
Update the documentation of `GET /company/time-off-types` and add `legacy_category` + adding it to `TimeOffTypeResource`
=> add field `legacy_category` to `TimeOffTypeResource` and `/company/time-off-types`

personio-auth-api.yaml, personio-personnel-data-api-oa3.yaml
* fix: remove /auth from Personnel API section
* fix: expand current /auth with X-Personio-Partner-ID and X-Personio-App-ID parameters
=> fix: remove /auth from Personnel API section

personio-personnel-data-api-oa3.yaml
Request an archived report results in 400 Bad Request
=> [AR-4195] Bad request when report is archived

Personio - Public API Collection.postman_collection.json
Adding the Postman collection to the GitHub repo so it can be added to [the Developer Hub Introduction page](https://developer.personio.de/reference/introduction).
=> Added Postman collection to repo

common-components-v2.json
* Introduce LinkObject
* Update MetaObject to use links as an object of (key: string, value: LinkObject)
* Remove duplicated MetaObject definition in CreatedObject
* Fix null paths
=> [PAPI-DEV] Update link references for meta object

personio-personnel-data-api-oa3.yaml
This example has been removed and should be re-added
=> NO-PAPI: adds missing example for EmployeesResponse
